name: QA
on:
  push:
    branches:
      - "15.0"
  pull_request:
    branches:
      - "*"
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{matrix.python-version}}
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: ${{runner.os}}-${{matrix.python-version}}-pre-commit
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files
